<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>RedirectFix</RootNamespace>
    <AssemblyName>RedirectFix</AssemblyName>
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <PropertyGroup>
    <GameInstallDir>A:\VintageStory\</GameInstallDir>
    <GameLibBinDir>$(MSBuildThisFileDirectory)..\..\VintagestoryLib\bin\$(Configuration)\net10.0\</GameLibBinDir>
    <ApiBinDir>$(MSBuildThisFileDirectory)..\..\bin\$(Configuration)\net10.0\</ApiBinDir>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="VintagestoryAPI">
      <HintPath>$(ApiBinDir)VintagestoryAPI.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="VintagestoryLib">
      <HintPath>$(GameLibBinDir)VintagestoryLib.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(GameInstallDir)Lib\0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

</Project>
